### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by sakurachian666** [HCIS-Lab/Action-slot#1]
Hello, thank you very much for your open-source spirit. I am very interested in your work and encountered several issues while running `pip install -e .`. There is no `setup.py` file.

**Comment by HankKung** [comment]
Hi,

Thank you for your interest in our project. I have updated the file with a new and compact requirements.txt and the corresponding install instruction in readme. Please try again and let me know if there's any issue.

Thank you!
